### ISSUE TITLE
getPlaylist(): TypeError: Cannot read property 'shortBylineText' of undefined

### ISSUE THREAD

**Issue by alverated** [VincentJonathan/scrape-yt#20]
`const results = await scrapeYt.getPlaylist("PLaYtGORLdHDIOZVNovduRmZBuoTGVOGAS");`

but using the playlist id from your example works fine.
`const results = await scrapeYt.getPlaylist("PLx65qkgCWNJIgVrndMrhsedBz1VDp0kfm");`

so I was thinking that this will happen if the playlist contains Deleted/Private Videos?

**Comment by SuspiciousLookingOwl** [comment]
4c5a4c3419d1ca3d5ca83c6487f34ee9a6abf378 should fix it, thanks!

Publishing new version on npm soon.

**Comment by alverated** [comment]
cool... thanks!
