### ISSUE TITLE
playlistSidebarSecondaryInfoRenderer undefined when to getting playlist

### ISSUE THREAD

**Issue by joshgare** [VincentJonathan/scrape-yt#22]
When using scrape-yt to scrape YouTube playlists I am getting the following the error:

```
Cannot read property 'playlistSidebarSecondaryInfoRenderer' of undefined.
```

This error occurred when trying to get the playlist with ID: `RDCLAK5uy_mfut9V_o1n9nVG_m5yZ3ztCif29AHUffI `.

This was done with the following code running v1.4.5 of scrape-yt:

```
await scrapeYt.getPlaylist("RDCLAK5uy_mfut9V_o1n9nVG_m5yZ3ztCif29AHUffI")
```

One other point to add is that I was trying to obtain 10 or so other playlists at the same time, so it might be a throttle kicking in?

**Comment by SuspiciousLookingOwl** [comment]
Thank you for reporting this.

This happens when you are trying to get playlist without channel information. Fixing it very soon.

**Comment by SuspiciousLookingOwl** [comment]
Please update to v1.4.6 and try again! If the issue still persists, feel free to reopen this issue 😄

**Comment by joshgare** [comment]
Unreal turnaround - you beat me with my fork and incoming PR 👏🏼. Will report back!

EDIT: Everything is working as expected- thanks again!
