### ISSUE TITLE
[BUG] Unexpected token } in JSON at position 10688

### ISSUE THREAD

**Issue by th13n-h4ck3r** [VincentJonathan/scrape-yt#26]
**Describe the bug**
Not sure when, but after updating to 1.4.6. This happens with all playlist ID

**To Reproduce**
Use any playlist ID. I tested the one in the documentation "PLx65qkgCWNJIgVrndMrhsedBz1VDp0kfm"
And call `getPlaylist(playlistId)`

**Expected behavior**
You should get the following error:
Unexpected token } in JSON at position 10688
    at JSON.parse (<anonymous>)
    at Object.parseGetPlaylist (...\node_modules\scrape-yt\dist\common\parser.js:274:36)
    at ...\node_modules\scrape-yt\dist\index.js:162:64
    at step ...\node_modules\scrape-yt\dist\index.js:54:23)
    at Object.next (...\node_modules\scrape-yt\dist\index.js:35:53)
    at fulfilled (...\node_modules\scrape-yt\dist\index.js:26:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Screenshots**
[Here](https://imgur.com/a/xtoNszI) is a test code that I used

**Comment by SuspiciousLookingOwl** [comment]
Can replicate, `getVideo` seems to be broken too, fixing this ASAP.

**Comment by SuspiciousLookingOwl** [comment]
Version 1.4.7 should fix this, please update the package and try again.

Thank you for reporting this issue. 😁
