### ISSUE TITLE
Search query isn't URI encoded

### ISSUE THREAD

**Issue by KareemH** [VincentJonathan/scrape-yt#4]

**Comment by KareemH** [comment]
![image](https://user-images.githubusercontent.com/40571613/80162155-83293980-85a0-11ea-822f-a2ea4503e3fb.png)

Every time I run my server, the videoId isn't scraped at all. I even use the maxRetryCount code as well. The probability of not scraping is high now, although it was working just a few days ago. Sadly, I can't replicate what search query caused this because I am looping through an array of 220 music artists

**Comment by SuspiciousLookingOwl** [comment]
What version are you using? That seems to be an older version, you can upgrade to v1.0.11 (`npm update scrape-yt`) and try it again, i made many improvement on scraping in v1.0.11 (https://github.com/VincentJonathan/scrape-yt/issues/2#issuecomment-617866538)

**Comment by KareemH** [comment]
I'm using the most recent version. When I reverted to an older version, scraping seems to be fine. In total, I scrape 220 songs, but maybe around 5 songs peculiarly scrape the wrong video ID

For instance:
![image](https://user-images.githubusercontent.com/40571613/80227547-c8d71800-861b-11ea-92a2-814a1c0c463b.png)
The search query is the artists name + title name + "official music video". The video description above the youtube video is different from the actual youtube video
![image](https://user-images.githubusercontent.com/40571613/80227657-f1f7a880-861b-11ea-96d7-656e44e47204.png)
![image](https://user-images.githubusercontent.com/40571613/80227856-3c792500-861c-11ea-92f8-37f9d6a10252.png)
These are just a few examples

Sorry for the excessive opening of issues! Hope you can figure it out :)

**Comment by SuspiciousLookingOwl** [comment]
Whoops my bad, i didn't encode URI Component on the search keyword. The `&` symbol on the search keyword messed the search up. Update to v1.0.12 and try again (d1b60d545492415e99a64d35c952d1a210f4ddc3).

Thanks again for reporting this. I'm going to close this, feel free to open it again if the problem still persist.
