### ISSUE TITLE
Enhancement : Duration on the Video object from a video search

### ISSUE THREAD

**Issue by SteeledSlagle13** [VincentJonathan/scrape-yt#8]
Would it be possible to return the duration when using
`.getVideo(videoID)`

I am currently chaining calls to get the duration because the .getVideo doesnt grab the duration
```JS
scrapeYt.getVideo(videoId).then((videoMain: Video) => {
                            scrapeYt.search(videoMain.title).then((videoInfos: Video[]) => {
...
```

would be awesome if this is possible!!!!

**Comment by SuspiciousLookingOwl** [comment]
Added on d63fb432158ae4093df442791ccf86e40d0d60f0! Upgrade to version 1.2.1 😄

**Comment by SteeledSlagle13** [comment]
You’re amazing!!! Thank you! 😁
