### ISSUE TITLE
simpleText undefined when trying to get viewCount

### ISSUE THREAD

**Issue by KareemH** [VincentJonathan/scrape-yt#9]
![image](https://user-images.githubusercontent.com/40571613/82135120-e89dce00-97cc-11ea-8043-b227efb9b2fc.png)
I am looping through movies in from the Movie Database API and an error s occurring when scraping viewCount. I don't know if this affects the videoId

The query in the parameter is the title of the movie + " trailer", so basicially `${title_of_movie} trailer`
These are the list of songs I am looping through:

<details>
  <summary>Movie List</summary>

Action Jackson
Buena Vista Social Club
The Red Violin
Rosetta
The Brave Little Toaster to the Rescue
The Bird People in China
The Love Letter
8 ½ Women
Besieged
Finding Graceland
Dr. Quinn Medicine Woman: The Movie
A Lesson Before Dying
You Can Thank Me Later
Alien Arsenal
Black Light
The Unexpected Mrs. Pollifax
The Jesse Ventura Story
Teenage Space Vampires
Bruce Almighty
Dogville
Ichi the Killer
Scorched
The Ghost of Lord Farquaad
The In-Laws
Shade
The Barbarian Invasions
Down
Deep Blue
Yossi & Jagger
Lupin the Third: Voyage to Danger
Blackball
Seducing Doctor Lewis
The Rage in Placid Lake
Martha, Inc.: The Story of Martha Stewart
Valentin
The Era of Vampires
Ice Bound - A Woman's Survival at the South Pole
Stealing Rembrandt
Die Hard: With a Vengeance
Little Odessa
Forget Paris
Amateur
Mosquito
Cyborg Cop III
The Granny
Play Time
White Dwarf
Spenser: A Savage Place
The Black Bomber
Gramps
Life 101
Ghosts of Gettysburg
The Show Formerly Known as the Martin Short Show
Evander Holyfield vs. Ray Mercer
A Night to Die For
Destination Vegas
TypeError: Cannot read property 'title' of undefined
    at /Users/kareem/Downloads/Spring 2020/CSCI 39548 (Web Development)/CSCI-39548-NostalgiaNow/nostalgia-master/index.js:606:56
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Addicted to Love
Brassed Off
Poison Ivy: The New Seduction
David Blaine: Street Magic
Changing Habits
The Designated Mourner
Behind Enemy Lines
Weapons of Mass Distraction
Anastasia
Invisible Mom
Kounterfeit
The Lost World: Jurassic Park
Blackwater Trail
The Apocalypse
Patton: A Tribute to Franklin J. Schaffner
Rampage
ECW Buffalo Invasion
Psycho Diver: Soul Siren
Hostage High
Demon Fighter Kocho
Mission: Impossible II
In the Mood for Love
Dinosaur
Road Trip
Small Time Crooks
Our Lips Are Sealed
Sailor Moon S the Movie: Hearts in Ice
Cheaters
Nico and Dani
Nang Nak
Growing Up Brady
Harlan County War
Mermaid
Murder, She Wrote: A Story to Die For
Sleepy Hollow: Behind the Legend
The Linda McCartney Story
The Debut
Lady Audley's Secret
Luminous Motion
Eating Air
Terminator Salvation
Night at the Museum: Battle of the Smithsonian
Mega Shark vs. Giant Octopus
Dance Flick
The Warlords
The Girlfriend Experience
Eden Log
How Bruce Lee Changed the World
Spring Breakdown
Vengeance
Tormented
Everyman's War
The Fear Chamber
Nick Swardson: Seriously, Who Farted?
Steppin: The Movie
Copyright Criminals
Eric Clapton and Steve Winwood - Live from Madison Square Garden
Russell Brand in New York City
Together: The Hendrick Motorsports Story
Jo Koy: Don't Make Him Angry
Legend
About a Boy
The Importance of Being Earnest
Igby Goes Down
Derailed
Brewster's Millions
Sweet Sixteen
Respiro
Ten
Ararat
Deserter
Ten Minutes Older: The Trumpet
Close to Leo
M*A*S*H: 30th Anniversary Reunion
Night At The Golden Eagle
Late Marriage
Washington Heights
Five Aces
Scared Silent
All Around The Town
Mission: Impossible
Ashes of Time
Flipper
Electra
Norma Jean & Marilyn
Heaven's Prisoners
Naked Souls
Earth
Power 98
A Friend's Betrayal
Over the Wire
The Siege at Ruby Ridge
A Boy Called Hate
For Which He Stands
Josh Kirby... Time Warrior: Last Battle for the Universe
Too Fast Too Young
Prem Granth
Portraits of a Killer
Thrill
Divididos: En vivo en MTV
Indiana Jones and the Kingdom of the Crystal Skull
Face/Off
Æon Flux
Changeling
Wendy and Lucy
Son of Rambow
The Flock
The Edge of Heaven
A Christmas Tale
Heavy Metal in Baghdad
Ocean Flame
Deadwater
The Devil's Ground
Dr. Jekyll and Mr. Hyde
Automaton Transfusion
Cloud 9
Johnny Mad Dog
Grindstone Road
Mystery of the Crystal Skulls
Better Things
Godzilla
As Good as It Gets
Fear and Loathing in Las Vegas
Tron
The Brave Little Toaster Goes to Mars
The Opposite of Sex
April
Gargantua
Under the Skin
Storm Chasers: Revenge of the Twister
Tainted
Provocateur
Broadway Damage
Night Time
Dirty Little Secret
Urban Legends
Natalie Merchant: Ophelia
Perfect Lies
Horseshoe
The Exotic Time Machine
Shrek the Third
Stomp the Yard
Sicko
WΔZ
Water Lilies
Stuck
Jesse Stone: Sea Change
The Mad
Joe Strummer: The Future Is Unwritten
Chop Shop
Big Man Japan
Have Dreams, Will Travel
And Along Come Tourists
Magicians
Madame Tutli-Putli
Careless
The Apocalypse
'Til Lies Do Us Part
Jellyfish
Shrek
Pearl Harbor
Human Nature
Truth or Consequences, N.M.
Conspiracy
New Alcatraz
Battle Queen 2020
R.O.D - Read or Die
The Perfect Wife
Submerged
Lan Yu
Ram Dass: Fierce Grace
All Access: Front Row. Backstage. Live!
Like Mother Like Son: The Strange Story of Sante and Kenny Kimes
Memories from the Sweet Sue's
The Making of Jaws 2
PTKHO
Memories, Dreams & Addictions
Nevermore: [2001] San Jose, California
Angel Dust: [2001] Live in San Jose, CA
Undisputed III: Redemption
MacGruber
Fair Game
You Will Meet a Tall Dark Stranger
Kites
Family Guy Presents: Something, Something, Something, Dark Side
Holy Rollers
Virginia
Witchville
Perrier's Bounty
Fairfield Road
Father of My Children
Mutant Vampire Zombies from the 'Hood!
Cultures of Resistance
Kooky
The Truth
Sneeze Me Away
Two in the Wave
Blood Junkie
Anderson's Cross
The Da Vinci Code
Over the Hedge
The Break-Up
Hollow Man II
Tristan & Isolde
Southland Tales
See No Evil
Severance
Desperation
Mulberry Street
Red Road
Brave Story
White Skin
Zidane: A 21st Century Portrait
The Witches Hammer
It Waits
Salvador (Puig Antich)
The Perfect Marriage
Sinful
Pineapple
Star Wars: Episode III - Revenge of the Sith
The Longest Yard
Dominion: Prequel to the Exorcist
The Muppets' Wizard of Oz
Into the Sun
The Last Drop
The God Who Wasn't There
Inuyasha the Movie: Affections Touching Across Time
6ixtynin9
Dinotopia: Quest for the Ruby Sunstone
Don't Come Knocking
Three Times
Two Drifters
Our Fathers
McLibel
Descent
Mondovino
The Circle
Ghost Lake
Erkan & Stefan 3
Shrek 2
The Assassination of Richard Nixon
Mysterious Skin
2046
Modigliani
Stateside
Marebito
Our Music
The Lion in Winter
Exiles
Omagh
Cat Stevens: Majikat
Star Spangled to Death
Reversible Errors
Thunderstruck
The Voice Behind the Mouse
Pearl Harbor: A Day of Infamy
Larry the Cable Guy: Git-R-Done
Party Animalz
Live Forever: The Rise and Fall of Brit Pop

</details>

**Comment by SuspiciousLookingOwl** [comment]
Update to 1.2.2!

Also looks like the search result from your keyword doesn't show what you really want, it sometimes gives random video, not the trailer of the movie. I think you need to make the keyword more specific, i recommend adding movie release year to the keyword and make the keyword a little simpler when it's too long.
